"""Auto-generated migration

Revision ID: 030adab5838f
Revises: 81cb6cb9b0ef
Create Date: 2023-05-11 21:20:23.653346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030adab5838f'
down_revision = '81cb6cb9b0ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
