"""Auto-generated migration

Revision ID: 0515c954a694
Revises: e34d05981f62
Create Date: 2023-05-10 19:32:34.416276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0515c954a694'
down_revision = 'e34d05981f62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
