"""Auto-generated migration

Revision ID: 0b057fcc6a8f
Revises: c84a58d40632
Create Date: 2023-05-10 19:34:43.946229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b057fcc6a8f'
down_revision = 'c84a58d40632'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
