"""Auto-generated migration

Revision ID: 395581f8e772
Revises: 0b057fcc6a8f
Create Date: 2023-05-10 19:35:13.224971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395581f8e772'
down_revision = '0b057fcc6a8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
