"""Auto-generated migration

Revision ID: 6058480abbdc
Revises: cff46b19db1f
Create Date: 2023-05-11 18:46:12.126466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6058480abbdc'
down_revision = 'cff46b19db1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
