"""Auto-generated migration

Revision ID: 81cb6cb9b0ef
Revises: 6058480abbdc
Create Date: 2023-05-11 20:45:27.017209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81cb6cb9b0ef'
down_revision = '6058480abbdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
