"""Auto-generated migration

Revision ID: 9ad422fcba20
Revises: 7423946e1f38
Create Date: 2023-05-10 22:38:09.585653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad422fcba20'
down_revision = '7423946e1f38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
