"""Auto-generated migration

Revision ID: a53849d0edb1
Revises: d6607e7b1083
Create Date: 2023-05-14 19:33:45.137313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53849d0edb1'
down_revision = 'd6607e7b1083'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
