"""Auto-generated migration

Revision ID: af8c9d2fb26d
Revises: 030adab5838f
Create Date: 2023-05-11 21:21:40.373144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8c9d2fb26d'
down_revision = '030adab5838f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
