"""Auto-generated migration

Revision ID: c84a58d40632
Revises: 0515c954a694
Create Date: 2023-05-10 19:34:26.826361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84a58d40632'
down_revision = '0515c954a694'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
