"""Auto-generated migration

Revision ID: cff46b19db1f
Revises: 9ad422fcba20
Create Date: 2023-05-10 22:46:06.634432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff46b19db1f'
down_revision = '9ad422fcba20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
