"""Auto-generated migration

Revision ID: d5fadc0b63ad
Revises: 395581f8e772
Create Date: 2023-05-10 20:26:36.129037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fadc0b63ad'
down_revision = '395581f8e772'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_content', table_name='posts')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_posts_content', 'posts', ['content'], unique=False)
    # ### end Alembic commands ###
