"""Auto-generated migration

Revision ID: e34d05981f62
Revises: 1ab4901830a2
Create Date: 2023-05-10 19:32:16.324742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34d05981f62'
down_revision = '1ab4901830a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
