"""Auto-generated migration

Revision ID: f9b2cbe1ab3d
Revises: d5fadc0b63ad
Create Date: 2023-05-10 20:26:48.920468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b2cbe1ab3d'
down_revision = 'd5fadc0b63ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.String(), nullable=True))
    op.create_index(op.f('ix_posts_content'), 'posts', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_content'), table_name='posts')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
