permissions = {'admin': {'posts:create': False,
           'posts:createBulk': False,
           'posts:delete': False,
           'posts:find': False,
           'posts:findOne': False,
           'posts:update': False},
 'public': {'posts:create': False,
            'posts:createBulk': False,
            'posts:delete': False,
            'posts:find': True,
            'posts:findOne': False,
            'posts:update': False},
 'user': {'posts:create': False,
          'posts:createBulk': False,
          'posts:delete': False,
          'posts:find': False,
          'posts:findOne': False,
          'posts:update': False}}